version: '3.8'

services:
  sql1:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: azuresqledge
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    volumes:
      - sql1_data:/var/opt/mssql
    restart: always

volumes:
  sql1_data:
