version: '3.8'
 
services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/tailscale:/var/run/tailscale
      - /var/cache/tailscale:/var/cache/tailscale
    environment:
      - TS_AUTHKEY=${tailscaleAuthkey}
      - TS_ACCEPTROUTER=1
      - TS_SUBNET_ROUTES=1
