version: '3.8'

services:
  stirling-pdf:
    container_name: stirling_pdf
    image: frooodle/s-pdf:latest
    ports:
      - '8081:8080' #<Host Port>:<Container Port> 
    volumes:
      - /location/of/trainingData:/usr/share/tesseract-ocr/5/tessdata
      - /location/of/extraConfigs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false