version: '3.8'

services:
  dashy:
    image: lissy93/dashy:latest
    container_name: dashy
    ports:
      - "4000:8080" #<Host Port>:<Container Port> 
    volumes:
      - ${PWD}/user-data/conf.yml:/app/user-data/conf.yml
    restart: always